import { jsPDF } from 'jspdf';
import type { ScanItem } from '../types';

export function exportScanToPdf(scan: ScanItem) {
  const doc = new jsPDF();

  // Header Banner
  doc.setFillColor(18, 18, 26);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(37, 99, 235);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('ScamShield AI', 14, 20);

  doc.setTextColor(200, 200, 200);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Cybersecurity Threat Analysis Report', 14, 28);
  doc.text(`Generated: ${new Date(scan.timestamp).toLocaleString()}`, 140, 28);

  // Divider
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(1);
  doc.line(14, 45, 196, 45);

  // Overview Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Scan Metadata', 14, 55);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Scan ID: ${scan.id}`, 14, 65);
  doc.text(`Scan Vector: ${scan.type}`, 14, 72);
  doc.text(`Target / Input: ${scan.target}`, 14, 79);

  // Risk Score Badge
  const isDanger = scan.riskLevel === 'Critical' || scan.riskLevel === 'High';
  doc.setFillColor(isDanger ? 239 : 16, isDanger ? 68 : 185, isDanger ? 68 : 129);
  doc.rect(14, 88, 182, 24, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`RISK EVALUATION: ${scan.riskLevel.toUpperCase()}`, 20, 98);
  doc.text(`Scam Probability Score: ${scan.scamProbability}%`, 20, 106);

  // Breakdown Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('2. AI Threat Analysis & Breakdown', 14, 125);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const explanationLines = doc.splitTextToSize(`Explanation: ${scan.result.explanation || 'N/A'}`, 180);
  doc.text(explanationLines, 14, 135);

  let currentY = 135 + (explanationLines.length * 6);

  if (scan.result.reasoning && scan.result.reasoning.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.text('Key Risk Indicators:', 14, currentY + 5);
    currentY += 12;
    doc.setFont('helvetica', 'normal');
    scan.result.reasoning.forEach((reason) => {
      doc.text(`• ${reason}`, 18, currentY);
      currentY += 6;
    });
  }

  // Recommended Actions
  currentY += 5;
  doc.setFont('helvetica', 'bold');
  doc.text('3. Recommended Immediate Security Actions', 14, currentY);
  currentY += 8;
  doc.setFont('helvetica', 'normal');

  const actions = scan.result.recommendedActions || [
    'Do not click links or download attachments.',
    'Verify sender credentials directly through official helplines.'
  ];

  actions.forEach((act) => {
    doc.text(`[!] ${act}`, 18, currentY);
    currentY += 6;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('ScamShield AI Confidential Report - Generated by ScamShield Threat Intelligence Engine', 14, 285);

  doc.save(`ScamShield_Report_${scan.id}.pdf`);
}
